### ISSUE TITLE
Flag enumerations.

### ISSUE THREAD

**Issue by Aberro** [HexaEngine/Hexa.NET.ImGui#10]
Could you add FlagsAttribute to flag enumerations? Currently, using bitwise operators with enums gives warnings which I had to disable for every method, as it's ill-advised to disable these warnings solution-wise.

**Comment by JunaMeinhold** [comment]
Really? Because i don't get any warnings, i mean it would be better for debugging anyway, since VS shows you the flag parts instead of just the number. But there is the issue with identifying Flags and non Flags enums.

**Comment by JunaMeinhold** [comment]
Update, added a heuristic in the generator, making final tests and then publish the new version on nuget

**Comment by JunaMeinhold** [comment]
Done. Nuget packages should be available any minute.
