### ISSUE TITLE
Project name repeats in generated items names like: ImPlot.ImPlotGetPlot

### ISSUE THREAD

**Issue by J8-8N** [HexaEngine/Hexa.NET.ImGui#15]
Hello, thank you for the awesome up-to-date bindings. In ImPlot, files functions.125.cs and functions.126.cs it seems the generator didn't remove the project name from the names of items so a very common method like ImPlot::GetPlot() became ImPlot.ImPlotGetPlot() instead of ImPlot.GetPlot(). And all the other items in those files too. Thank you

**Comment by JunaMeinhold** [comment]
Thanks for pointing that out. I fixed it right now, you just have to wait until the nuget packages are available.

**Comment by J8-8N** [comment]
Thank you! In ImPlot functions.124.cs line 1799 I think public static ImDrawList* GetPlotDrawList() should return ImDrawListPtr instead to suit how the Hexa.Net.ImGui does similar GetDrawList methods.

**Comment by JunaMeinhold** [comment]
Fixed it, i will wait for your reply if there is anything else that catches your eye before releasing it, I don't want to annoy people by very frequent updates. And additionally you can just implicitly cast it to ImDrawListPtr when doing
```cs
ImDrawListPtr draw = ImPlot.GetPlotDrawList();
```
