### ISSUE TITLE
Proposal to Include Backend Bindings in CSharp Libraries for Reusability

### ISSUE THREAD

**Issue by JunaMeinhold** [HexaEngine/Hexa.NET.ImGui#17]
I've received some suggestions about including backends in CSharp bindings (#16) to make it easier for developers to reuse existing, well-tested backends (e.g., for Windows, macOS, and Linux) from CImGui, rather than having to create custom solutions from scratch. This could help streamline development across platforms when using CSharp bindings.

The backends would be shipped in a extra nuget package (or multiple) to stay dependency free.

- [x] Win32
- [x] GLFW
- [x] SDL2
- [x] OpenGL2
- [x] OpenGL3
- [x] Vulkan
- [x] D3D9
- [x] D3D10
- [x] D3D11
- [x] D3D12
- [x] Metal
- [x] OSX
- [x] Android

**Comment by JunaMeinhold** [comment]
No problem, i already found a way.

![image](https://github.com/user-attachments/assets/aebb2217-c159-4506-b24a-d11e65e9f6dd)

(see io.BackendXXX)
![image](https://github.com/user-attachments/assets/db50b830-650e-4359-bac6-1afff3d74dea)

**Comment by JunaMeinhold** [comment]
The only problem i have is I don't know if that requires me now to ship sdl2 and glfw dlls on linux/unix based systems on windows i can just do /DELAYLOAD: but i don't have that much experience with coding on windows

![image](https://github.com/user-attachments/assets/e38516e8-f8be-41ef-bb69-a88d2282c2f3)

**Comment by J8-8N** [comment]
Awesome! Please make it GLFW 3.4+ if they need included

**Comment by JunaMeinhold** [comment]
I will simply use the vcpkg version
![image](https://github.com/user-attachments/assets/38e70dbd-4b3e-453e-99be-e28a9649032c)

**Comment by JunaMeinhold** [comment]
I have a problem i can only embed the backends into cimgui and not as separate shared lib which isn't a good solution, since that means every lib like sdl2 and glfw3 are by that dependencies. A solution for that problem would be to convert the backends to cimgui and then dynamic link to cimgui, but that would need a major change in those backend files, it might be possible to automate but that would need time.

**Comment by JunaMeinhold** [comment]
Update: i found a workaround.

**Comment by JunaMeinhold** [comment]
Any idea why this happens? The glu32.lib exists clearly for arm64. It only happens on arm64 for windows, when i build locally on my machine everything works.

![image](https://github.com/user-attachments/assets/85899af1-7d9e-4d22-9846-722df8445195)

![image](https://github.com/user-attachments/assets/bd6dfbd4-cf19-4d15-b72e-2da16667fd1e)

**Comment by JunaMeinhold** [comment]
Next Question, should i make independent packages for each backend type or a all in one package or maybe both?

**Comment by J8-8N** [comment]
Sorry I can't help, I'm an embedded C dev dealing mostly with highly constrained resources and discovering CSharp, GUI and Github tools.

Are the backends drop-in replacement for each other? I guess that's the core question to decide how to package them.

Unrelated and a bit premature but could you consider adding some functions of GLFW like setWindowHint, setWindowAttrib and their getWindowHint and getWindowAttrib equivalent so users can configure stuff a little from CSharp? Thank you very much

**Comment by JunaMeinhold** [comment]
The only thing that's to consider in packing them is that some uses prefer SDL2 over GLFW or vice versa you definitely don't need both at the same time. And the backend for Win32 (another windowing) has no dependencies that have to be shipped along the implementation dll means i can just ship it as base same goes for D3D11 D3D12 OpenGL Vulkan they are all part of the operating system/graphics driver. The only thing that would happen if you call D3D11 eg windows related functions on linux or any other os that's not windows then it would crash, but luckily you can check which os you are on in c# with:
```cs
RuntimeInformation.IsOSPlatform(OSPlatform.Windows)
```

I will not add functions for GLFW for that you have to go grab any wrapper that allows access to the underlying pointers like Silk.NET.GLFW does, same goes for SDL2, Silk also has a SDL2 lib available but i have one too. I will probably make a wrapper for GLFW soon too, but they will not be shipped with the package, to satisfy users that might prefer lib x over y.

**Comment by J8-8N** [comment]
So the block of code from main() here https://github.com/ocornut/imgui/blob/master/examples/example_glfw_opengl3/main.cpp#L38 to ImGui_ImplGlfw_InitForOpenGL (line 86) will be handled by the user with a third-party GLFW binding?

**Comment by JunaMeinhold** [comment]
yeah just like this
![image](https://github.com/user-attachments/assets/e3892231-55b2-44e9-9480-65ffc0342822)

**Comment by JunaMeinhold** [comment]
Small update: i made bindings for GLFW (3.4) https://github.com/HexaEngine/Hexa.NET.GLFW

**Comment by JunaMeinhold** [comment]
I uploaded the backends on nuget and source is available in backends branch.
![image](https://github.com/user-attachments/assets/969b4ee2-aa73-4f45-9a58-bde3cacba2ba)

**Comment by J8-8N** [comment]
Hello and congratulations, this is awesome.

D3D11 example, OpenGL3 example and GLFW example all worked on the first try!

I'm trying to bruteforce a GLFW/OpenGL3 example:
![image](https://github.com/user-attachments/assets/bebc1c62-a7a1-4f13-9a2c-31d19bd8a17f)
But GLFW.CreateWindow returns an Hexa.NET.GLFW.GLFWwindowPtr
then ImGuiImplGLFW.InitForOpenGL expects an Hexa.NET.ImGui.Backends.GLFW.GLFWwindowPtr
and I'm unsure how to resolve this best.

Thank you!

**Comment by JunaMeinhold** [comment]
I'll upload a minimal example soon. And add some changes too, but what you do basically is this then

![image](https://github.com/user-attachments/assets/1caf46cb-904f-4b7b-8ac7-0ece50ffde18)

**Comment by JunaMeinhold** [comment]
Here: https://github.com/HexaEngine/Hexa.NET.ImGui/blob/backends/ExampleGLFWOpenGL3/Program.cs

**Comment by J8-8N** [comment]
Awesome thank you very much. Tried the example on Windows and Linux so far but have not tried anything fancy yet

**Comment by JunaMeinhold** [comment]
I tested it with my widget collection which has many custom widgets and it seems to work fine.
![image](https://github.com/user-attachments/assets/ee17f3e9-c230-4595-8bc7-0df3517ca6c4)

**Comment by J8-8N** [comment]
Would you have an opinion on the GLFW+DirectX11 combo? It's in the CImGui examples but not in the ImGui examples and I wonder if there's a good reason for that. https://github.com/cimgui/cimgui/tree/docking_inter/backend_test/example_glfw_dx11

Thank you

**Comment by JunaMeinhold** [comment]
Of course you can do GLFW+D3D11 but you have to make something like this https://github.com/HexaEngine/Hexa.NET.ImGui/blob/master/ExampleD3D11%2FD3D11Manager.cs and the setup is just larger in comparison to GLFW+GL and SDL2 is better for game engines. While GLFW is just for windowing SDL2 is a multimedia library.

**Comment by JunaMeinhold** [comment]
And i can't test the metal backends anyway. Since i don't own a mac

**Comment by J8-8N** [comment]
Thank you very much!

You might be interested to add this quirky bugfix from the GLFW examples back:
![image](https://github.com/user-attachments/assets/999431ce-0922-4a60-b9dd-c9bfc3d024b2)

**Comment by JunaMeinhold** [comment]
Thoughts on my new wrapper, is there anything missing? (I don't use OpenGL that much)
https://github.com/HexaEngine/Hexa.NET.OpenGL
