### ISSUE TITLE
Hexa.NET.ImNodes is no longer updated?

### ISSUE THREAD

**Issue by qian-o** [HexaEngine/Hexa.NET.ImGui#18]
I can only find version 2.1.6 on NuGet.
![image](https://github.com/user-attachments/assets/09000742-d7d5-47e5-9423-ce0736d58e27)

**Comment by JunaMeinhold** [comment]
Probably forgot to upload it will check in a minute.

**Comment by JunaMeinhold** [comment]
i uploaded it now. Thanks for pointing that out.
![image](https://github.com/user-attachments/assets/c813a34f-9737-4c52-aa99-bbdb4601c4bc)

**Comment by qian-o** [comment]
Thanks for your maintenance.
