### ISSUE TITLE
cimplot_impl like cimgui_impl

### ISSUE THREAD

**Issue by J8-8N** [HexaEngine/Hexa.NET.ImGui#20]
Hello,

I was trying the new backends (thank you again so much) when I realized that my trial-project (in CPP) required a few lines changed in the ImGui core. I tried to code around the issue in CSharp but it led nowhere. Thankfully I noticed your cimgui_impl project yesterday and its GitHub workflows (new to me). So I modified ImGui, ran your Actions, replaced the library files and tada: it all works like in my dreams.

Would you maybe publish a cimplot_impl project like your cimgui_impl project so users could compile their own ImPlot DLLs with their changes?

So it's not about regenerating bindings or adding functions or types but just making quick changes to existing functions that would map 1:1 to your existing bindings.

Thank you very much

**Comment by JunaMeinhold** [comment]
Do you mean this?
https://github.com/JunaMeinhold/cimplot
https://github.com/JunaMeinhold/cimguizmo
https://github.com/JunaMeinhold/cimnodes

**Comment by J8-8N** [comment]
Hello, to be sure, cimplot should be compiled alongside cimgui/cimgui or your HexaEngine/cimgui_impl? Thank you

**Comment by JunaMeinhold** [comment]
cimgui_impl is just for the backends. cimgui has the actual overloads. cimgui_impl is build without cimgui and doesn't have it as dependency.

git clone --recursive https://github.com/cimgui/cimgui.git
git clone --recursive https://github.com/JunaMeinhold/cimplot.git
git clone --recursive https://github.com/JunaMeinhold/cimguizmo.git
git clone --recursive https://github.com/JunaMeinhold/cimnodes.git

![image](https://github.com/user-attachments/assets/e7975209-a2db-45ce-826a-5827db8ccd17)

![image](https://github.com/user-attachments/assets/d0f808e5-da7d-4763-b69c-1e32aabac0c7)

![image](https://github.com/user-attachments/assets/9ecb0093-933a-42e1-9791-897b94971870)

And done!

**Comment by J8-8N** [comment]
Thank you, it worked smoothly indeed. Now I'll try to have it done by Github keep natives for every platform like you.

**Comment by JunaMeinhold** [comment]
https://github.com/HexaEngine/Hexa.NET.ImGui/tree/master/.github/workflows

**Comment by JunaMeinhold** [comment]
Can I closed this issue?

**Comment by J8-8N** [comment]
Yes sure, it all works, thank you
