### ISSUE TITLE
Call ImGui.DestroyContext() throws Access violation exception.

### ISSUE THREAD

**Issue by qian-o** [HexaEngine/Hexa.NET.ImGui#21]
I prefer to release resources before closing the window, but after calling ImGui.DestroyContext(), the process will freeze for a while and return Code: -1073741819 (0xc0000005).

![image](https://github.com/user-attachments/assets/6acec3f6-f374-4b27-b31b-e41a677d2067)

I tried to modify the instance provided in the repository to release resources after the window is closed, and a similar exception will be thrown.

![image](https://github.com/user-attachments/assets/3bc5003d-4a1b-4bbd-bf76-573180869324)

In the previous version, I didn't encounter this problem.

**Comment by JunaMeinhold** [comment]
Could you provide me the exact moment where you call it?
With code please 
(I'm not home at the moment)

**Comment by qian-o** [comment]
I forked the current repository and modified the code of the ExampleOpenGL3 project to call Dispose after closing the window to recycle ImGui resources.
https://github.com/qian-o/Hexa.NET.ImGui

**Comment by JunaMeinhold** [comment]
It has probably something to do with Program.RegisterHook, look for references, you have to unhook before destroying anything, if not done sdl2 will send messages to a dangling pointer.

**Comment by JunaMeinhold** [comment]
This
https://github.com/HexaEngine/Hexa.NET.ImGui/blob/master/ExampleFramework%2FApp.cs#L68

**Comment by qian-o** [comment]
The Dispose() method is called after the loop exits, and the functions in hooks are not called.
![image](https://github.com/user-attachments/assets/f8d7c506-67f2-434e-b1ad-cee5bdc08b05)

**Comment by JunaMeinhold** [comment]
I think i fixed it could you check again? 
Also maybe enable mixed mode debugging.

How to enable mixed-mode debugging:
![image](https://github.com/user-attachments/assets/395745b7-05c9-4938-bff9-3097009469c5)
![image](https://github.com/user-attachments/assets/7fadfdad-c145-44d1-b777-fabd70e98107)

**Comment by qian-o** [comment]
I made some modifications to your latest code.
![image](https://github.com/user-attachments/assets/ec3bb09d-e2ae-4373-9cb6-2a473dea18d3)

Unfortunately, there are still some problems with it.
![image](https://github.com/user-attachments/assets/eb84f868-fa9c-4e57-b8d4-70f0ea632a44)

**Comment by JunaMeinhold** [comment]
> I made some modifications to your latest code. ![image](https://private-user-images.githubusercontent.com/84434846/377524353-ec3bb09d-e2ae-4373-9cb6-2a473dea18d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNzc5NTEsIm5iZiI6MTcyOTE3NzY1MSwicGF0aCI6Ii84NDQzNDg0Ni8zNzc1MjQzNTMtZWMzYmIwOWQtZTJhZS00MzczLTljYjYtMmE0NzNkZWExOGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDE1MDczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNWE2NWJmMGM2MTFlYmUxY2YxZDNlODJmOTY5ZWJmYTg4YWFiODU2YjUwYmQ4NGE5OGY4NjM4MzJlYTMzMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sQXhlc_pSoVE3DQ3sGGjeIjX3p_6HDa184kKYEuAUf4)
> 
> Unfortunately, there are still some problems with it. ![image](https://private-user-images.githubusercontent.com/84434846/377524064-eb84f868-fa9c-4e57-b8d4-70f0ea632a44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNzc5NTEsIm5iZiI6MTcyOTE3NzY1MSwicGF0aCI6Ii84NDQzNDg0Ni8zNzc1MjQwNjQtZWI4NGY4NjgtZmE5Yy00ZTU3LWI4ZDQtNzBmMGVhNjMyYTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDE1MDczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwZDZkYWFkYWZjNDg2NWQ3ZTY1NjdiZWM3M2RjY2YwMzM2MzM4Njk3NGQ5MGM1MjY2OTAzODk2ZGNhMzRiYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ohKr07lv8_ELUMmR13gGp36Mohv1KoZ8EhBiRAeGUpc)

not needed see App.Run()

**Comment by JunaMeinhold** [comment]
![image](https://github.com/user-attachments/assets/68ed5eff-88a9-47a5-bb48-9de4d2034f71)

**Comment by qian-o** [comment]
This approach does work, thank you for your help.
