### ISSUE TITLE
FreeType support

### ISSUE THREAD

**Issue by J8-8N** [HexaEngine/Hexa.NET.ImGui#22]
Hello,

would you maybe consider FreeType support?

Your new examples have a convenient TTF font loading method so I tried it and something didn't feel right. After trying a few different fonts thinking they were the issue, I read this: 

https://github.com/ocornut/imgui/blob/master/misc/freetype/README.md

Where there is a great example of my exact "issue":
![Example](https://user-images.githubusercontent.com/8225057/107550178-fef87f00-6bd0-11eb-8d09-e2edb2f0ccfc.gif)

Thank you!

**Comment by JunaMeinhold** [comment]
it's a cimgui generator option
![image](https://github.com/user-attachments/assets/514826f5-3159-4f22-b4b7-246480a6685e)

**Comment by JunaMeinhold** [comment]
And it would probably cause issues with the backends. Since we use the native backends means we don't have control over that.
A workaround would be to gamma correct the pixel data on cpu before backend init, but i don't know if that even works.
![image](https://github.com/user-attachments/assets/6f7f8cc7-6c35-467d-97b0-4baca7facd05)

**Comment by JunaMeinhold** [comment]
Additionally it would create bloat
![image](https://github.com/user-attachments/assets/6bc42369-d242-4e5c-a654-10c041832748)

**Comment by apodtele** [comment]
FreeType returns _colorless_ alpha channel map, aka pixel coverage. Client is free to blend any foreground and background color combination, with or without gamma correction. Only client knows knows or assumes appropriate gamma too. FreeType does not assume anything.

**Comment by JunaMeinhold** [comment]
@apodtele 
Not entirely true FreeType has the Pixel format FT_PIXEL_MODE_BGRA.

**Comment by JunaMeinhold** [comment]
Theoretically it can be done on CPU side but that requires a change in imgui

**Comment by NotNite** [comment]
I would be interested in this for [emoji support](https://github.com/ocornut/imgui/blob/master/docs/FONTS.md#using-colorful-glyphsemojis). No ImGui bindings for C# seem to be both actively maintained and support FreeType.

**Comment by JunaMeinhold** [comment]
I think i got it working. :3
![image](https://github.com/user-attachments/assets/c37301a7-d18f-41b4-9e5b-93617c042f8d)

**Comment by JunaMeinhold** [comment]
Could take a while until i can publish everything, i have to modify/fork cimgui since it doesn't support uint32 for glyph ranges which is required for many emojis.

**Comment by JunaMeinhold** [comment]
Almost done, testing a few things first.

To enable the loading of colored fonts, you only need to do this:
![image](https://github.com/user-attachments/assets/2d79996d-d59d-4b3b-b341-37e4e3ca97a8)

**Comment by JunaMeinhold** [comment]
Published on nuget.
![image](https://github.com/user-attachments/assets/719eafb1-1f9c-4089-aade-c4424734789f)

**Comment by NotNite** [comment]
No issues here! I had to migrate [my codebase](https://github.com/NotNite/ImSky) from legacy Veldrid to Silk+Hexa+SDL+OpenGL, but everything works smoothly now. As a first time user of this library, thank you very much!!!

![image](https://github.com/user-attachments/assets/8f6ac0a4-a35f-4b16-a40e-262ba6a8659a)

Unrelated suggestion: might be nice to publish an ExampleFramework-like library that makes setting things up easier for standalone projects (I'm making a desktop app). Having various hooks for init steps (like setting custom flags on IO, a custom window icon, fonts, etc) should solve the problem that it's too abstracted away as well.

**Comment by JunaMeinhold** [comment]
I made this thing, tested on windows and linux. A very simple to use UI "Framework" and thin abstraction of ImGui
https://github.com/HexaEngine/Hexa.NET.KittyUI

**Comment by JunaMeinhold** [comment]
This is a usage example.
```cs
using Hexa.NET.ImGui;
using Hexa.NET.ImGui.Widgets;
using Hexa.NET.ImGui.Widgets.Dialogs;
using Hexa.NET.KittyUI;
using Hexa.NET.KittyUI.Graphics;
using TestApp;

AppBuilder appBuilder = new();
appBuilder.SetTitle("Test App");
appBuilder.AddWindow<MainWindow>(true, true);
appBuilder.Run();

namespace TestApp
{
    public class MainWindow : ImWindow
    {
        private string? file;
        private Image? image;

        protected override string Name => "Main Window";

        public override unsafe void DrawContent()
        {
            ImGui.Text("Hello, World!");

            if (file != null)
            {
                ImGui.Text($"Selected file: {file}");
            }

            if (ImGui.Button("... (open)"))
            {
                OpenFileDialog dialog = new();
                dialog.AllowMultipleSelection = true;
                dialog.Show(Callback);
            }

            if (ImGui.Button("... (save)"))
            {
                SaveFileDialog dialog = new();
                dialog.Show(Callback);
            }

            if (ImGui.Button("Load Texture"))
            {
                LoadTexture("icon.png");
            }

            if (image != null)
            {
                ImGui.Image(image, new(256, 256));
            }
        }

        private void LoadTexture(string path)
        {
            Task.Run(() =>
            {
                image = Image.LoadFromFile(path);
            });
        }

        private void Callback(object? sender, DialogResult result)
        {
            if (sender is OpenFileDialog dialog)
            {
                if (result == DialogResult.Ok)
                {
                    file = dialog.SelectedFile;
                }
            }
            if (sender is SaveFileDialog saveFileDialog)
            {
                if (result == DialogResult.Ok)
                {
                    file = saveFileDialog.SelectedFile;
                }
            }
        }
    }
}
```

**Comment by J8-8N** [comment]
Thank you very much Juna
