### ISSUE TITLE
Add backend to dx9 implementation

### ISSUE THREAD

**Issue by DestroyerDarkNess** [HexaEngine/Hexa.NET.ImGui#25]
Hi, great project, congratulations.

Is it possible that you can add implementation to DirectX9?

**Comment by JunaMeinhold** [comment]
Will do, but I'll probably publish the backend when i can release ImGui 1.91.5 (just waiting cimgui to update, I might fork it and do it myself)

**Comment by DestroyerDarkNess** [comment]
I understand, I'll be waiting.

Thanks for replying, best regards.
