### ISSUE TITLE
Library weight (mb)

### ISSUE THREAD

**Issue by Drakenroft** [HexaEngine/Hexa.NET.ImGui#27]
Hi!
Just found this amazing binding (and your other project HexaEngine that i will keep following for sure, it seems damn amazing already!), i'm thinking of switching from ImGui.NET that i'm currently using for my small game engine, to your binding, but i noticed that the size of the packages are quite differents yours weight 21.36mb while ImGui.NET is 3.71mb,
It's a small difference in fact but i'm trying to keep my project size as small as possible (not a real reason behind it, i just want to make it extremely portable like Godot).
I wanted to ask if there is way to strip down the size of the package other than the usual dotnet arguments? (to make an example i don't need the included Backends, since i got my own in OpenGL, can i compile the library without them, or is there any pre-compiled package that i'm missing which is already stripped to only imgui?).

Thanks a lot, for your project anyway it truly is amazing!

**Comment by JunaMeinhold** [comment]
Hi, The package is just that large because of support for multiple .net versions and more OS platforms supported, the backends are in a separate package, if you compile with dotnet publish -r win-x64 for example then only the win x64 binaries are getting copies to output.

**Comment by JunaMeinhold** [comment]
For more info visit https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-publish
