### ISSUE TITLE
Scaling not working properly in example

### ISSUE THREAD

**Issue by orosbogdan** [HexaEngine/Hexa.NET.ImGui#32]
When running the opengl 3 example, if scaling multiple times on an axis, when the model is scaled so much that it starts having a portion of it outside the viewing frustum, the model gets distorted.

![image](https://github.com/user-attachments/assets/07ce3cf5-898d-4cfc-8a8a-7dcc42e1d67b)

**Comment by JunaMeinhold** [comment]
That's a ImGuizmo problem and not from this library, because the 3D model is not actually 3D it's a 3D Cube projected to the screen to 2D coords, then naturally if you exit the frustrum you get distortions, using a regular 3D model with a 3D pipeline this problem wouldn't occur.

**Comment by JunaMeinhold** [comment]
In short it's a limitation of ImGui/ImGuizmo since it's 2D only. (A mathmatical limitation)

**Comment by JunaMeinhold** [comment]
For real 3D shape drawing you could use another project from me for that purpose. (Those are real 3D Shapes)
https://github.com/HexaEngine/Hexa.NET.DebugDraw
